name: Demo Example
run-name: 
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo This demo file shows a 
      - run: echo very basic and easy-to-understand workflow.
