pipeline {
    agent any
    stages {
        stage('Checkout IMS') {
            steps {
                dir("IMS") {
                    checkout([
                        $class: 'GitSCM',
                        branches: [[name: '*/main']],
                        doGenerateSubmoduleConfigurations: false,
                        extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'CalibrationResults']],
                        submoduleCfg: [],
                        userRemoteConfigs: [[url: 'https://github.com/mhy20401/Inventory-Management-System-MERN-CRUD-App.git']]
                    ])
                }
                dir("IMS/CalibrationResults") {
                    bat "dir /p"
                }
            }
        }
        stage('Create Mongo Database') {
            steps {
                dir("IMS") {
                    bat "mongosh --host localhost --port 27017 -f buildmongo.js"
                }
            }
        }
        stage('Run server') {
            parallel {
                stage('Backend') {
                    steps {
                        dir("IMS/CalibrationResults/Backend") {
                            bat "npm run server"
                        }
                    }
                }
                stage('Frontend') {
                    steps {
                        dir("IMS/CalibrationResults/Frontend/inventory_management_system") {
                            bat "npm start"
                        }
                    }
                }
            }
        }
    }
}